/*
    Copyright (C) 2016 Apple Inc. All Rights Reserved.
    See LICENSE.txt for this sample’s licensing information
    
    Abstract:
    Basic mesh class that exposes buffers generated by Model I/O for rendering with Metal
*/

import Foundation
import Metal
import MetalKit
import SceneKit.ModelIO

// Assume the data in both the vertexBuffer & indexBuffer are packed_floatn
// if the mesh is instantiated from an MDLMesh method.
class Mesh {
    // The following properties are public
    var vertexBuffer: MTLBuffer!
    var vertexBufferOffset: Int!
    var primitiveType: MTLPrimitiveType!
    var indexBuffer: MTLBuffer!
    var indexCount: Int!
    var indexType: MTLIndexType!
    var indexBufferOffset: Int!

    var vertexDescriptor: MTLVertexDescriptor!

    init?() {
    }
}
